server:
  port: 8000
#  servlet:
#    context-path: /springboot

spring:
  profiles:
    active: dev
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.blog.domain.test
  #  type-aliases-package: com.battcn.entity
  #  # 驼峰命名规范 如：数据库字段是  order_id 那么 实体字段就要写成 orderId
  #  configuration:
  #    map-underscore-to-camel-case: true
  ########## 通用Mapper ##########
  # 主键自增回写方法,默认值MYSQL,详细说明请看文档
  identity: MYSQL
  mappers: tk.mybatis.mapper.common.Mapper
  # 设置 insert 和 update 中，是否判断字符串类型!=''
  not-empty: true
  # 枚举按简单类型处理
  enum-as-simple-type: true
  ########## 分页插件 ##########

pagehelper:
    helperDialect: mysql
logging:
  level:
    com.blog.bloginfra.user : debug